### ISSUE TITLE
Where to register a user account so I can use to generate api token?

### ISSUE THREAD

**Issue by StevenZiu** [Cloudeya/coronavirusapi-wrapper#12]
**Example Code**

```js
```

**Expected behavior, if applicable**

### Your Environment

| software                     | version
| ---------------------------- | -------
| coronavirusapi-wrapper       |
| node             			   |
| npm              			   |
| Operating System 			   |

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by 0xnu** [comment]
@StevenZiu Details is here: https://www.covid19api.dev/#token
